### ISSUE TITLE
Notebook Mode

### ISSUE THREAD

**Issue by Mandarancio** [fabiocolacio/Marker#104]
As well something like a notebook mode would be nice to integrate, with different folder (e.g. one for each subject) and each folder contains the notes of the subject.

**Comment by fabiocolacio** [comment]
I don't really like this idea. We decided that there would be a tree-view sidebar to open files with, so I think this feature would be redundant. The tree-view is more flexible because it is unassuming about the work flow of the user, whereas the feature you describe above is only really useful for one particular kind of work flow.

**Comment by Mandarancio** [comment]
Sure I understand! :)
