### ISSUE TITLE
Add: Insert Sketch

### ISSUE THREAD

**Issue by Mandarancio** [fabiocolacio/Marker#105]
Something I miss in most of the editors is some kind of "add a sketch" where you can draw something with your mouse or touchscreen and add the sketch in the document directly (and eventually modify it in the future).

I think especially today with hybrid laptop and touchscreen everywhere it would be very useful (especially when taking notes in class).

**Comment by fabiocolacio** [comment]
I like the idea but then we have to store the image data somewhere in another file, and the user will have to manage the files separately.

Then again, the user already has to manage multiple files if there are other images linked.

Im not sure if this can be done with Gnome systems, but we might be able to create some kind of custom MIME type so that our app creates folders with a ``.marker`` extension, and the filesystem could recognize it not as a folder, but as a file for our app. This way we could store a markdown documents as well as any images, in one folder, but to the user it is a self-contained file that opens Marker when double-clicked.

**Comment by Mandarancio** [comment]
My idea was simple to generate a ```FILENAME_sketch_#.png``` file and to link it in the markdown as image then is up to the user to not delete it. 

It would be nice than to have some action (e.g. ctrl+click over an image tag in the editor) to open local images on the sketcher dialog and edit it.

**Comment by fabiocolacio** [comment]
This could work. We can check if the user right-clicks on an image in the preview, and the contextual menu can have a button to edit the image. This could open up our custom image editing feature in a new window, or possibly allow the user to choose another app to edit with.

**Comment by fabiocolacio** [comment]
It could be nice for adding signiatures into documents or annotating other images.

**Comment by Mandarancio** [comment]
this [code](https://github.com/tindzk/GTK/blob/master/examples/scribble-simple/scribble-simple.c) can be used as base/
