### ISSUE TITLE
Create own editor style

### ISSUE THREAD

**Issue by rotsix** [fabiocolacio/Marker#117]
Hi !

As some popular editors, that would be great to be able to create some custom themes, or to modify them.

Thanks !

**Comment by Mandarancio** [comment]
As now it should be possible to add custom css theme in the ```/usr/local/share/com.github.fabiocolacio.marker/styles/``` folder but would be better to add a local user folder (```~/.local/share/com.github.fabiocolacio.marker/styles/``` where to store user themes.

Maybe it would be also better to reduce the name to ```marker``` without all the naming space overhead.

**Comment by rotsix** [comment]
Hi !
Wasn't talking about preview style, but editor's one, in `Settings > Editor > Highlight sntax with theme:`

If i can put them in `~/.local/.../styles/`, is there any link or existing theme location ?

**Comment by Mandarancio** [comment]
Sorry my bad, no for the moment we are only using the default ones but it should not be hard to look for user ones using the ```gtk_source_style_scheme_manager_append_search_path```.
I will look into it.

**Comment by fabiocolacio** [comment]
I believe the style choosers mentioned in issue #89 also have a button to choose a custom theme.

**Comment by rotsix** [comment]
Yep. In facts, all that is missing is an option to duplicate an existing theme, and then we can edit it with our hands

**Comment by fabiocolacio** [comment]
Ok so it turns out that all gnome apps that use ``GtkSourceView`` such as *Gedit* and *Gnome Builder*, all look for styles in specific locations. [More info here](https://wiki.gnome.org/Projects/GtkSourceView/StyleSchemes).

Those locations are:

* ``~/.local/share/gtksourceview-3.0/styles/ ``
* ``/usr/share/gnome/gtksourceview-3.0/styles/ ``
* ``/usr/local/share/gtksourceview-3.0/styles/ ``
* ``/usr/share/gtksourceview-3.0/styles/ ``

If you place a custom theme in one of those locations, it will be found by Marker and any other program using ``GtkSourceView``.
