### ISSUE TITLE
When the preview is refreshed, the scrollbar resets to the top

### ISSUE THREAD

**Issue by fabiocolacio** [fabiocolacio/Marker#13]

**Comment by fabiocolacio** [comment]
As of commit https://github.com/fabiocolacio/Marker/commit/f2e8fff848c0f479ee8099bda7f1f1ab5968def9 , the auto-refresh is only triggered when editing after editing the document, so as long as you do not make changes, the scroll location will remain unaffected.

This makes it much easier to view the preview when not editing, however it can still be annoying when making changes or manually refreshing with the refresh button.

**Comment by fabiocolacio** [comment]
Scrolling for WebKitWebView is not exposed with a GtkScrolledWindow. Scrolling will have to be controlled through Javascript.

**Comment by fabiocolacio** [comment]
As of commit 0fe645a4b73ea3b495de968cc74980f7a0d53763, the view scrolls down to where it is supposed to be using javascript. This sometimes causes graphical glitches due to improper timing, which still needs to be resolved.

**Comment by fabiocolacio** [comment]
Javascript is too slow, and the page will jerk up and down with the current implementation. WebExtensions might be the best solution.

**Comment by Mandarancio** [comment]
The scroll position is now stored and restored after each modification, however it would be nice to be able to click on the preview and go to the corresponding markdown line and vice-versa.  
Do you think it would be useful?

**Comment by fabiocolacio** [comment]
Im closing this issue because now it seems to be resolved in the autoscroll branch.

**Comment by nick87720z** [comment]
I checked, how it works, using release 2020.04.04. It still jumps, but not always to top - looks like it just misses.
Although I don't know webkit-gtk enough good to know, is it possible to calculate position for specific element - but what if it just utilized singe dedicated tag, implicitly placed under cursor or where central line. And instead of scrolling to exact position, it could be just request to navigate to that tag. Of course, if problem is in exact position determining rather than mentioned timing issue.
