### ISSUE TITLE
Export to PDF presentation?

### ISSUE THREAD

**Issue by jumpinggoofballs** [fabiocolacio/Marker#163]
Is it possible to tweak the PDF export feature to also allow exporting the document as a presentation in .pdf format _a la_ Marp?

See here what I am referring to: https://www.youtube.com/watch?v=wwDdyDC6b1M

AFAIK, pandoc can do this with some options and settings, but it would be nice if this was integrated straight into the editor. 

Many thanks!

**Comment by Mandarancio** [comment]
I'm working on it, in commit  215ddd1 I included the last version of scidown that support for the class `beamer` *a la* `Marp` syntax for slides. Morover I created a simple `beamer` css based on the `github2` but is far less nicer that the one that `Marp` uses (but is css so it can be easily improved). 

To export in pdf I'm having issues to set the correct page size to the automatic exporter, however you can always print in pdf and chosing the correct page size (around 8.3in x 6.25in) and margins.

To use the `beamer` class put in your `YAML` header `class: beamer`. If any tilte, authors or affiliaition 
is defined in the header it will be presented as first slide.

below a screenshot:

![screenshot beamer](https://user-images.githubusercontent.com/276686/37216891-4d17342a-23bc-11e8-90b9-fde2da2ea950.png)


Let me know what you think and what are your need.

**Comment by jumpinggoofballs** [comment]
Looks very promising already!

I have to say I'm not a huge fan of the beamer themes, and I do agree that the Marp default one is great. Marp is licensed under MIT so I see no reason why that theme could not be used either as is or taken as inspiration. Could always ask the author nicely + give credit. 

Size is going to be a tricky one though. That and perhaps aspect ratio? But so long as aspect ratio can be prescribed in the YAML, I guess sizing can be mostly covered by the pdf viewer. So just give it a reasonably high def default, and maybe allow for custom specifications for size in the YAML again?

**Comment by Mandarancio** [comment]
Yes it should be possible to use the Marp [**themes**](https://github.com/yhatt/marp/tree/master/sass) (probably some adaptation is still needed) however Marp use [Sass](https://sass-lang.com/) instead of CSS and I do not have enough time to convert and understand their syntax. But any help is more then welcome! 

The aspect ratio is now 4:3 and at 800x600 pixels the idea to customize it via yaml seems nice, I will look into it. The real problem is how to set the pdf page size because even if in the css is specified the exporter still use the standard A4 format.

In the css I'm doing the following

```css
@media print {
  @page
  {
      size: 8.3in 6.25in;
      margin: 0;
      size: landscape;
  }
}
```

But nothing happen... I'm wondering if using  [wkhtml2pdf](https://wkhtmltopdf.org/) would improve the results ....

**Comment by Mandarancio** [comment]
**UPDATE** after some improvement on both html generation and css styling the `beamer` class looks better and work with most of the styles (the `pubcss` and `scidown` are not supported as they are optimized for A4 pages).

Printing the pdf using a custom print setting of the correct size also work fine to export the presentation, however the internal pdf exporter does not yet support custom paper sizes.

Here a screenshot using the `solarized` theme.

![screenshot-2018-3-10 title 1](https: //user-images.githubusercontent.com/276686/37237547-b60c11fa-2414-11e8-8364-6414ac098d5a.png)

**Comment by jumpinggoofballs** [comment]
Wow... that's something I would use already!

For sass to css conversion, could just use a web-based compiler like: https://www.sassmeister.com/ . Sass goes in, css comes out.

For paper size, maybe fix the width to standard A4, and then adjust the height as a function of the aspect ratio? That should be a perfectly sane default, and then if things can be customised in the YAML that should cover all the bases, no?

**Comment by Mandarancio** [comment]
Since commit 1dcd77e better pdf export is implemented, now the paper size set in the yaml header is used to export to pdf as well no white margin are added to the pdf exported.
However even if the orientation (landscape / portrait) is set during the export process webkit does seems to ignore it.... I'm working on a solution so for now the presentations does not look nice.

The paper size setting is set using the keyword `paper` in the header and the available settings are:

```
A0 - A6
B0 - B6
C0 - C6
b0j - b6j
letter, executive and legal
```

**Comment by jumpinggoofballs** [comment]
Hmm... Can you provide an example YAML page size instruction so I can test this on the latest git master version? 

And also add that to the beamer example in the README.md / documentation?

For anyone else interested in using this feature I have found that printing to .pdf file with the dimensions: 

**`221mm : 166mm with 0 margins`** works perfectly fine. 

However, if one would want to export / print in 16:9 aspect ratio, then everything is offcentre towards the left. -- Could this be done to work in that aspect ratio as well?

**Comment by Mandarancio** [comment]
A simple example of paper-size is the following:

```markdown
---
class: beamer
title: A Simple Presentation
author: Martino Ferrari
paper: A4
---
```

However none of the current paper format is satisfactory and I will add new formats (e.g., what @jumpinggoofballs  did  propose above). 

For the aspect ratio there is the problem of the CSS as well to adjust, but I think I will be able to find some simple solution, like two different classes, one `beamer_43` for `4:3` ratio and one `beamer_169` for the `16:9` ratio.

Finally  I added a simple example of presentation in the folder ```test/``` of the project.

**Comment by jumpinggoofballs** [comment]
For the record, the dimensions for a 16:9 aspect ratio that seem to work for me (1080p @ 13.3"):
**`294mm : 166mm with 0 margins`**

**Comment by Mandarancio** [comment]
I added two new paper size classes: `4:3` and `16:9` to export presentation as PDF. An example with generated pdf is in the folder `test/`, I used the `GitHub` css style for exporting it. 

The main issue is the missing of nice and optimized css style for presentations. 
The second issue is more general and is the fact that any link functionality is lost due to the use of the internal `webkit` print  pdf  api.

**Comment by jumpinggoofballs** [comment]
`4:3` works! Almost perfectly, in fact. 

There might be a tweak in there where height could be 1 or 2px more for the papersize, for the purposes of fullscreen alignment when used in conjunction with a pdf reader (like evince). There is a very slight height shift when moving to and from the first and last page because of how stuff gets padded out, but I'm not sure how much of that can be helped from the Marker export.

`16:9` is problematic on my end. I have attached the resulting pdf. Once again it seems like the content is rendered larger than the page size, resulting in stuff going off-centre and blank pages being inserted every other page: [output.pdf](https://github.com/fabiocolacio/Marker/files/1844857/output.pdf)

I don't understand the beamer paper size stuff, and how that relates to the CSS but I can do CSS. Is there something I can do to help on the themes, for example?

**Comment by Mandarancio** [comment]
I updated `scidown` and now it should work (remember to update sub-modules otherwise nothing will happen)! 

I will make a wiki page with the html structure for both classic and presentation documents as well as explaining where to find the css files and its function.

**Comment by jumpinggoofballs** [comment]
So export to PDF for beamer presentations works just fine with Github theme + 4:3 aspect and with the added wiki for the CSS stuff, I can tweak things to fix any small issues. I am closing this issue, and we can leave the 'Themes needed' one open instead.
