### ISSUE TITLE
Code syntax highlighting is not always monospace

### ISSUE THREAD

**Issue by zesterer** [fabiocolacio/Marker#208]
The syntax highlighter sometimes decides to use fonts that aren't monospace. This is not pleasant to look at.

![image](https://user-images.githubusercontent.com/3268430/40058413-fb8b336a-5848-11e8-97d7-5627ba59736f.png)

**Comment by fabiocolacio** [comment]
@zesterer I updated the common stylesheet so that all code blocks have ``font-family: monospace``.

I'm not sure if this fixed it because I couldn't reproduce this issue.

To test it out, run the latest version of the code from git-master, or you can just replace the file in ``/usr/share/com.github.fabiocolacio.marker/common/scidown.css`` with the newest version in the repo in ``data/common``.
