### ISSUE TITLE
@include & inline image renders no content

### ISSUE THREAD

**Issue by raven78** [fabiocolacio/Marker#209]
Linux Mint 18.3
FlatPack app: Marker 2018.04.27

`@include(path.mg)` renders nothing
`![Some inline image](path.jpg)` renders `Some inline image` and no image

Error shown in the console:
```
(marker:2): GLib-GIO-CRITICAL **: 16:54:55.822: g_file_get_uri: assertion 'G_IS_FILE (file)' failed
```
![Marked Render Error](https://user-images.githubusercontent.com/3068958/40311615-08e6ed68-5d19-11e8-96e4-efeaab51f16e.png)

**Comment by raven78** [comment]
Taking a look at Inkscape, Gimp or VSCode might help. I'm using all three through flatpak an none have file acces issue. Inkscape can import and display embedded and linked images without a problem...

**Comment by fabiocolacio** [comment]
That's because the inkscape flatpak has full access to the filesystem enabled, rather than using flatpak "portals" to access files.

Other contributors were advocating that I not give full filesystem access, instead opting for other solutions, but it seems that we have little choice now. I have added access to the home directory in this latest update, which should be available in the next few days. If it solves this issue for you, please let me know.

**Comment by fabiocolacio** [comment]
I would rather not limit the functionality of the application for everyone just to cater to one package format.

For now, I added access to the home folder of the filesystem because too many important features simply do not work without it (exporting, printing, showing linked files, various command-line features, etc), but perhaps we can improve this in the future. After all, flatpak is still young, and new solutions and features will surely be added as time progresses.
