### ISSUE TITLE
Markdown lint support/integration [Feature Request]

### ISSUE THREAD

**Issue by pardaloupa** [fabiocolacio/Marker#216]
Hello,

Thank you very much for developing a robust Gnome friendly markdown application.

As someone who likes to follow coding styles and rules, I would love to have markdown lint integration within marker. I can see two markdown linters being available, [one](https://github.com/DavidAnson/markdownlint) based on node.js and [one](https://github.com/markdownlint/markdownlint) ruby based.

I believe this is something that will benefit all users so it is worth considering :+1:

**Comment by fabiocolacio** [comment]
I personally don't see the value in a linter for markdown.

For actual programming languages, a linter is useful because it can detect code that may cause undefined behavior, but markdown either works or it doesn't. If the code doesn't work, it will be reflected in the preview pane, removing the need for a linter.

Furthermore, we maintain a custom version of Markdown called Scidown, with features unavailable anywhere else, so if we wanted to add a linter, we would likely have to write one from scratch (or fork another linter).

To me, this feature doesn't seem to be worth the effort as very few people are likely to use it, and they could run one of the linters you mentioned from the command-line anyways.

**Comment by pardaloupa** [comment]
OK, thank you for the reply. I see where you are coming from. I was thinking more about having a way to check consistent writing style rather than correctness but I guess you are right, markdown is not an actual programming language. Maybe is my OCD kicking in when I see two markdown files that I wrote using different spacing, layouts etc. What i am saying is having a way to standardize writing style.

As you said I am already using the command line to check for issues while I am typing in marker. If there is no value then definitely no effort should be put into it, on the other hand maybe some sort of run external checker tool might be another option.

Maybe most people don't care about consistent writing style but I do. Regardless there are ways around it so please proceed as you see fit! I am just sharing my thoughts.
