### ISSUE TITLE
Release ZIP file "2018.07.03" contains code for "2018.03.09"

### ISSUE THREAD

**Issue by njam** [fabiocolacio/Marker#224]
It seems the two most recent releases have a ZIP file attached which contains the code from the old version "2018.03.09":
https://github.com/fabiocolacio/Marker/releases
https://github.com/fabiocolacio/Marker/releases/tag/2018.07.03
https://github.com/fabiocolacio/Marker/releases/tag/2018.04.27

I guess the ZIP file doesn't contain anything apart from what is in the repo already, so probably you could just remove the ZIP file, as GitHub provides a download link to download the given git tag as a ZIP file.

**Comment by fabiocolacio** [comment]
Hi @njam,

Thanks for the heads-up. I took a look at the zip file, and the code appears to be the correct version, but I just forgot to update the version number.

The archives provided by Github do not contain the git-submodules (which are dependencies needed to build the code), which is why I create my own release archives.
