### ISSUE TITLE
App menu migration

### ISSUE THREAD

**Issue by bertob** [fabiocolacio/Marker#244]
Application menus have been a source of usability issues since they were introduced, despite attempts to improve them. We are therefore aiming to end their use by 3.32.0. 

In Marker's case this would be pretty easy:
 - Remove app menu
 - Move contents to the hamburger menu on the right

See [the wiki page](https://gitlab.gnome.org/GNOME/Initiatives/wikis/App-Menu-Retirement) for design guidelines.

**Comment by fabiocolacio** [comment]
Hi @bertob,

As it stands right now, users have the ability to move the appmenu contents to the hamburger menu in Marker's preferences. There has been some discussion in #233 about using ``gtk_application_prefers_appmenu()`` to decide where it should go instead.

I imagine that this is the best solution, rather than removing the appmenu outright, as it will fit in better with older versions of GNOME and other DE's that use the appmenu still.

Are we wrong to assume that ``gtk_application_prefers_appmenu()`` will return ``false`` in future versions of GNOME where the appmenu is deprecated?

**Comment by bertob** [comment]
I think you're correct in assuming that, so there shouldn't be any problems :)

**Comment by AdrianVovk** [comment]
This is still broken for me. I didn't even know that marker had a settings page because A) My DE has no app menu and B) Marker didn't notice this and kept using it. Maybe it's better to remove the setting outright after-all?
